project_id = "xieqxulnumoagtyrrjgd"

[functions.ai-tutor]
verify_jwt = false

[functions.extract-text]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-notes]
verify_jwt = false
